openapi: 3.1.0
info:
  title: APIFiddle Sample Definition
  description: Example workspace
  version: 1.0.0

servers:
  - url: http://localhost:8085/v1
    description: Local development
  - url: https://client_svc:8085/v1
    description: Client service server

paths:
  /client_svc/receive_email_notification/v1:
    post:
      operationId: receiveEmailNotificationFromUserService
      tags:
        - email
      summary: Receive Email Notification from User Service
      parameters: []
      description: Receive email notification from User Service
      responses:
        "204":
          description:
            The request was successful, but there is no content to return in
            the response.
          content:
            application/json:
              schema:
                type: "null"
        "422":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
  /client_svc/pdf_ready/v1:
    post:
      operationId: notificationPdfIsReady
      tags:
        - pdf
      summary: Notification PDF is ready
      responses:
        "204":
          description:
            The request was successful, but there is no content to return in
            the response.
          content:
            application/json:
              schema:
                type: "null"
  /health:
    head:
      operationId: healthcheck
      summary: healthcheck
      responses:
        "200":
          description:
            The request was successful, and the server has returned the
            requested resource in the response body.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                required:
                  - data

tags:
  - name: email
  - name: pdf
