openapi: 3.1.0
info:
  title: Client Service API
  description: Client-facing service that receives notifications from user_svc about email delivery and PDF conversions
  version: 1.0.0

servers:
  - url: http://localhost:8085
    description: Local development
  - url: http://client_svc:8085
    description: Client service server (Docker)

paths:
  /client_svc/receive_email_notification/v1:
    post:
      operationId: receiveEmailNotificationFromUserService
      tags:
        - notifications
      summary: Receive email delivery notification from user_svc
      description: |
        Receives email delivery status notifications forwarded by user_svc/ForwardEmailNotificationController.

        **Caller**: user_svc/ForwardEmailNotificationController (via Clients.ClientSvcClient.push_notification)
        **Receiver**: client_svc/EmailNotificationController.receive

        The notification is received as a plain text message and logged. This is a fire-and-forget endpoint.
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              $ref: '#/components/schemas/EmailNotificationMessage'
            example: "Email sent successfully to user@example.com"
      responses:
        "204":
          description: Notification received successfully (fire-and-forget)
        "422":
          description: Failed to read request body
          content:
            text/plain:
              schema:
                type: string
                example: "[Client][EmailNotificationController] Unprocessable"
  /client_svc/pdf_ready/v1:
    post:
      operationId: notificationPdfIsReady
      tags:
        - notifications
      summary: Receive PDF ready notification from user_svc
      description: |
        Receives notification when image-to-PDF conversion is complete and the PDF is stored in MinIO.

        **Caller**: user_svc/NotifyImageConvertedController (via Clients.ClientSvcClient.notify_image_converted)
        **Receiver**: client_svc/PdfReadyController.receive

        The controller decodes the PdfReadyNotification protobuf and logs the information for the user.
      requestBody:
        required: true
        content:
          application/protobuf:
            schema:
              $ref: '#/components/schemas/PdfReadyNotification'
            example:
              user_email: "user@example.com"
              storage_id: "1699876543210_aBc123XyZ.pdf"
              presigned_url: "http://minio:9000/msvc-images/1699876543210_aBc123XyZ.pdf"
              size: 524288
              message: "Your PDF is ready! Size: 1920x1080, 512.0KB"
      responses:
        "204":
          description: Notification received successfully
        "422":
          description: Failed to decode PdfReadyNotification protobuf
          content:
            text/plain:
              schema:
                type: string
                example: "[PdfReady][PdfReadyController] Unprocessable Entity"
  /health:
    get:
      operationId: healthcheckGet
      tags:
        - health
      summary: Health check endpoint (GET)
      description: |
        Simple health check endpoint to verify service availability.

        **Controller**: client_svc/HealthController.check

        Returns 200 OK with "OK" text body.
      responses:
        "200":
          description: Service is healthy
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
    head:
      operationId: healthcheckHead
      tags:
        - health
      summary: Health check endpoint (HEAD)
      description: |
        Simple health check endpoint to verify service availability without response body.

        **Controller**: client_svc/HealthController.check

        Returns 200 OK with no body.
      responses:
        "200":
          description: Service is healthy

tags:
  - name: notifications
    description: Notification endpoints for email delivery and PDF conversion events
  - name: health
    description: Service health check endpoints

components:
  schemas:
    EmailNotificationMessage:
      type: string
      description: Plain text message from EmailResponse.message field
      example: "Email sent successfully to user@example.com"

    PdfReadyNotification:
      type: object
      description: PdfReadyNotification protobuf message
      required:
        - user_email
        - storage_id
        - presigned_url
        - size
        - message
      properties:
        user_email:
          type: string
          format: email
          description: Email of the user who initiated the conversion
          example: "user@example.com"
        storage_id:
          type: string
          description: PDF storage ID in MinIO
          example: "1699876543210_aBc123XyZ.pdf"
        presigned_url:
          type: string
          format: uri
          description: Temporary URL to view/download the PDF
          example: "http://minio:9000/msvc-images/1699876543210_aBc123XyZ.pdf"
        size:
          type: integer
          format: int64
          description: PDF size in bytes
          example: 524288
        message:
          type: string
          description: "Human-readable status message"
          example: "Your PDF is ready! Size: 1920x1080, 512.0KB"
