openapi: 3.1.0
info:
  title: Email Service API
  description: Email delivery service using Swoosh with SMTP/local adapter
  version: 1.0.0
servers:
  - url: http://localhost:8083
    description: Local development
  - url: http://email_svc:8083
    description: Email service server (Docker)

paths:
  /email_svc/send_email/v1:
    post:
      summary: Send email via Swoosh mailer
      operationId: sendEmail
      tags:
        - email
      description: |
        Sends an email using the configured Swoosh mailer adapter (SMTP or local).

        **Caller**: job_svc/Workers.EmailWorker (called by EmailSvcClient.send_email)
        **Receiver**: email_svc/DeliveryController.send

        Sends welcome or notification emails to users. Called after job_svc/EmailWorker processes the Oban job.
      requestBody:
        required: true
        content:
          application/protobuf:
            schema:
              $ref: '#/components/schemas/EmailRequest'
            example:
              user_id: "user123"
              user_name: "John Doe"
              user_email: "john.doe@example.com"
              email_type: "welcome"
      responses:
        "200":
          description: Email sent successfully
          content:
            application/protobuf:
              schema:
                $ref: '#/components/schemas/EmailResponse'
        "400":
          description: Unknown email type
          content:
            text/plain:
              schema:
                type: string
                example: "[Email][DeliveryController] Unknown email type"
        "422":
          description: Protobuf decode error
          content:
            text/plain:
              schema:
                type: string
                example: "[Email][DeliveryController] Bad Request"

  /health:
    get:
      summary: Health check endpoint (GET)
      operationId: healthCheckGet
      tags:
        - health
      description: |
        Simple health check endpoint to verify service availability.

        **Controller**: email_svc/HealthController.check

        Returns 200 OK with "OK" text body.
      responses:
        "200":
          description: Service is healthy
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
    head:
      summary: Health check endpoint (HEAD)
      operationId: healthCheckHead
      tags:
        - health
      description: |
        Simple health check endpoint to verify service availability without response body.

        **Controller**: email_svc/HealthController.check

        Returns 200 OK with no body.
      responses:
        "200":
          description: Service is healthy

tags:
  - name: email
    description: Email delivery operations via Swoosh
  - name: health
    description: Service health check endpoints

components:
  schemas:
    EmailRequest:
      type: object
      description: EmailRequest protobuf message
      required:
        - user_id
        - user_name
        - user_email
        - email_type
      properties:
        user_id:
          type: string
          description: User ID
          example: "user123"
        user_name:
          type: string
          description: User's full name
          example: "John Doe"
        user_email:
          type: string
          format: email
          description: Recipient email address
          example: "john.doe@example.com"
        email_type:
          type: string
          enum: [welcome, notification]
          description: Type of email to send
          example: "welcome"

    EmailResponse:
      type: object
      description: EmailResponse protobuf message
      required:
        - success
        - message
      properties:
        success:
          type: boolean
          description: Success indicator
          example: true
        message:
          type: string
          description: Status message
          example: "[Email][DeliveryController] New email sent to john.doe@example.com"
