openapi: 3.1.0
info:
  title: Image Service API
  description: Image to PDF conversion service using ImageMagick
  version: 1.0.0
servers:
  - url: http://localhost:8084
    description: Local development
  - url: http://image_svc:8084
    description: Image service server (Docker)

paths:
  /image_svc/convert_image/v1:
    post:
      summary: Convert image to PDF
      operationId: convertImage
      tags:
        - conversion
      description: |
        Converts PNG or JPEG image to PDF format using ImageMagick with configurable quality settings.

        **Caller**: job_svc/Workers.ImageConversionWorker (called by ImageSvcClient.convert_image)
        **Receiver**: image_svc/ConversionController.convert

        **Workflow:**
        1. Fetches image from provided URL (user_svc/ImageLoader endpoint)
        2. Converts to PDF using parallel ImageMagick processing
        3. Uploads PDF to MinIO S3 storage
        4. Returns acknowledgment with metadata to job_svc
        5. job_svc forwards result to user_svc for client notification
      requestBody:
        required: true
        content:
          application/protobuf:
            schema:
              $ref: '#/components/schemas/ImageConversionRequest'
            example:
              user_id: "user123"
              user_email: "user@example.com"
              image_url: "http://user_svc:8081/user_svc/image_loader/v1/1699876540000_original.png"
              image_data: ""
              input_format: "png"
              pdf_quality: "high"
              strip_metadata: true
              max_width: 0
              max_height: 0
              storage_id: "1699876540000_original.png"
      responses:
        "200":
          description: Conversion successful
          content:
            application/protobuf:
              schema:
                $ref: '#/components/schemas/ImageConversionResponse'
        "500":
          description: Conversion failed
          content:
            application/protobuf:
              schema:
                $ref: '#/components/schemas/ImageConversionResponse'

  /health:
    get:
      summary: Health check endpoint (GET)
      operationId: healthCheckGet
      tags:
        - health
      description: |
        Simple health check endpoint to verify service availability.

        **Controller**: image_svc/HealthController.check

        Returns 200 OK with "OK" text body.
      responses:
        "200":
          description: Service is healthy
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
    head:
      summary: Health check endpoint (HEAD)
      operationId: healthCheckHead
      tags:
        - health
      description: |
        Simple health check endpoint to verify service availability without response body.

        **Controller**: image_svc/HealthController.check

        Returns 200 OK with no body.
      responses:
        "200":
          description: Service is healthy

tags:
  - name: conversion
    description: Image to PDF conversion operations using ImageMagick
  - name: health
    description: Service health check endpoints

components:
  schemas:
    ImageConversionRequest:
      type: object
      description: ImageConversionRequest protobuf message
      required:
        - user_id
        - user_email
        - image_url
        - input_format
      properties:
        user_id:
          type: string
          description: User identifier
          example: "user123"
        user_email:
          type: string
          format: email
          description: User email for notification
          example: "user@example.com"
        image_url:
          type: string
          format: uri
          description: URL to fetch image from (points to user_svc/image_loader)
          example: "http://user_svc:8081/user_svc/image_loader/v1/1699876540000_original.png"
        image_data:
          type: string
          format: binary
          description: Should be empty (not used, image fetched via URL)
        input_format:
          type: string
          enum: [png, jpeg, jpg]
          description: Input image format
          example: "png"
        pdf_quality:
          type: string
          enum: [low, medium, high, lossless]
          description: PDF quality setting
          default: medium
          example: "high"
        strip_metadata:
          type: boolean
          description: Whether to remove EXIF metadata
          default: false
          example: true
        max_width:
          type: integer
          description: Maximum width (0 for no limit)
          default: 0
          example: 0
        max_height:
          type: integer
          description: Maximum height (0 for no limit)
          default: 0
          example: 0
        storage_id:
          type: string
          description: Original image storage ID for cleanup
          example: "1699876540000_original.png"

    ImageConversionResponse:
      type: object
      description: ImageConversionResponse protobuf message
      required:
        - success
        - message
      properties:
        success:
          type: boolean
          description: Whether conversion succeeded
          example: true
        message:
          type: string
          description: Status message
          example: "Conversion successful"
        pdf_data:
          type: string
          format: binary
          description: Empty (PDF stored in MinIO, not returned)
        input_size:
          type: integer
          format: int64
          description: Original image size in bytes
          example: 1048576
        output_size:
          type: integer
          format: int64
          description: PDF size in bytes
          example: 524288
        width:
          type: integer
          description: Image width in pixels
          example: 1920
        height:
          type: integer
          description: Image height in pixels
          example: 1080
        storage_id:
          type: string
          description: PDF storage ID (MinIO S3 key)
          example: "1699876543210_aBc123XyZ.pdf"
        original_storage_id:
          type: string
          description: Original image storage ID (for cleanup)
          example: "1699876540000_original.png"
