openapi: 3.1.0
info:
  title: Job Service API
  description: Asynchronous job processing service using Oban for emails and image conversion
  version: 1.0.0
servers:
  - url: http://localhost:8082
    description: Local development
  - url: http://job_svc:8082
    description: Job service server (Docker)

paths:
  /job_svc/enqueue_email/v1:
    post:
      summary: Enqueue email job in Oban
      operationId: enqueueEmail
      tags:
        - jobs
      description: |
        Receives user creation request and enqueues an asynchronous email job via Oban.

        **Caller**: user_svc/CreateUserController.create
        **Receiver**: job_svc/EmailSenderController.enqueue

        The job is processed by EmailWorker which calls email_svc to send the actual email.
      requestBody:
        required: true
        content:
          application/protobuf:
            schema:
              type: object
              description: UserRequest protobuf message
              properties:
                id:
                  type: string
                  description: User ID
                name:
                  type: string
                  description: User full name
                email:
                  type: string
                  format: email
                  description: Recipient email address
                type:
                  type: string
                  enum: [EMAIL_TYPE_WELCOME, EMAIL_TYPE_NOTIFICATION]
                  description: Type of email to send
              required:
                - id
                - name
                - email
                - type
            example:
              id: "user123"
              name: "John Doe"
              email: "john.doe@example.com"
              type: "EMAIL_TYPE_WELCOME"
      responses:
        "200":
          description: Email job enqueued successfully
          content:
            application/protobuf:
              schema:
                type: object
                description: UserResponse protobuf message
                properties:
                  ok:
                    type: boolean
                    description: Success indicator
                  message:
                    type: string
                    description: Status message with Oban job details
        "500":
          description: Failed to enqueue job
          content:
            application/protobuf:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  message:
                    type: string

  /job_svc/convert_image/v1:
    post:
      summary: Enqueue image-to-PDF conversion job
      operationId: convertImage
      tags:
        - jobs
      description: |
        Receives image conversion request and enqueues an asynchronous Oban job.

        **Caller**: user_svc/ConvertImageController.convert
        **Receiver**: job_svc/ImageController.convert

        The job is processed by ImageConversionWorker which calls image_svc to perform the actual conversion.
      requestBody:
        required: true
        content:
          application/protobuf:
            schema:
              type: object
              description: ImageConversionRequest protobuf message
              properties:
                user_id:
                  type: string
                  description: User ID
                user_email:
                  type: string
                  format: email
                  description: User email for notification
                image_url:
                  type: string
                  format: uri
                  description: URL to fetch image from (points to user_svc/image_loader)
                  example: "http://user_svc:8081/user_svc/image_loader/v1/1699876540000_original.png"
                image_data:
                  type: string
                  format: binary
                  description: Should be empty (not used, image fetched via URL)
                input_format:
                  type: string
                  enum: [png, jpeg, jpg]
                  description: Input image format
                pdf_quality:
                  type: string
                  enum: [low, medium, high, lossless]
                  description: PDF quality setting
                strip_metadata:
                  type: boolean
                  description: Whether to remove EXIF metadata
                max_width:
                  type: integer
                  description: Maximum width (0 for no limit)
                max_height:
                  type: integer
                  description: Maximum height (0 for no limit)
                storage_id:
                  type: string
                  description: Original image storage ID for cleanup
              required:
                - user_id
                - user_email
                - image_url
                - input_format
            example:
              user_id: "user123"
              user_email: "user@example.com"
              image_url: "http://user_svc:8081/user_svc/image_loader/v1/1699876540000_original.png"
              image_data: ""
              input_format: "png"
              pdf_quality: "high"
              strip_metadata: true
              max_width: 0
              max_height: 0
              storage_id: "1699876540000_original.png"
      responses:
        "200":
          description: Conversion job enqueued successfully
          content:
            application/protobuf:
              schema:
                type: object
                description: UserResponse protobuf message
                properties:
                  ok:
                    type: boolean
                    description: Success indicator
                  message:
                    type: string
                    description: Status message with Oban job ID
        "500":
          description: Failed to enqueue job
          content:
            application/protobuf:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  message:
                    type: string

  /health:
    get:
      summary: Health check endpoint (GET)
      operationId: healthCheckGet
      tags:
        - health
      description: |
        Simple health check endpoint to verify service availability.

        **Controller**: job_svc/HealthController.check

        Returns 200 OK with "OK" text body.
      responses:
        "200":
          description: Service is healthy
          content:
            text/plain:
              schema:
                type: string
                example: "OK"
    head:
      summary: Health check endpoint (HEAD)
      operationId: healthCheckHead
      tags:
        - health
      description: |
        Simple health check endpoint to verify service availability without response body.

        **Controller**: job_svc/HealthController.check

        Returns 200 OK with no body.
      responses:
        "200":
          description: Service is healthy

tags:
  - name: jobs
    description: Job enqueueing endpoints for async processing via Oban
  - name: health
    description: Service health check endpoints

components:
  schemas:
    ObanJob:
      type: object
      description: Oban background job representation
      properties:
        id:
          type: integer
        state:
          type: string
          enum: [available, scheduled, executing, retryable, completed, discarded, cancelled]
        queue:
          type: string
        worker:
          type: string
        args:
          type: object
        max_attempts:
          type: integer
        attempt:
          type: integer
        scheduled_at:
          type: string
          format: date-time
