openapi: 3.0.0
info:
  title: User Service API
  description: Handler Client requests and S3 image storage entrypoint
  version: 1.0.0
servers:
  - url: http://localhost:8081/v1
    description: Local development
  - url: https://user_svc:8081/v1
    description: User service server

paths:
  /user_svc/create_user/v1:
    post:
      summary: Create user and trigger email workflow
      operationId: createUser
      requestBody:
        required: true
        content:
          application/protobuf:
            schema:
              type: object
              properties:
                id:
                  type: string
                name:
                  type: string
                email:
                  type: string
                  format: email
                type:
                  type: string
                  enum: [welcome, notification]
      responses:
        '200':
          description: User created successfully
          content:
            application/x-protobuf:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /user_svc/notify_email_sent/v1:
    post:
      summary: Receive callback from job_svc after email sent
      operationId: notifyEmailSent
      requestBody:
        required: true
        content:
          application/x-protobuf:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                email:
                  type: string
                status:
                  type: string
      responses:
        '200':
          description: Notification received

  /user_svc/convert_image/v1:
    post:
      summary: Initiate image conversion workflow
      operationId: convertImage
      requestBody:
        required: true
        content:
          application/x-protobuf:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                user_email:
                  type: string
                image_data:
                  type: string
                  format: byte
                input_format:
                  type: string
                  enum: [png, jpeg, jpg]
      responses:
        '200':
          description: Conversion initiated
          content:
            application/x-protobuf:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string

  /user_svc/image_loader/v1/{job_id}:
    get:
      summary: Serve stored images to other services
      operationId: loadImage
      parameters:
        - name: job_id
          in: path
          required: true
          schema:
            type: string
          description: Job identifier for the stored image
      responses:
        '200':
          description: Image binary data
          content:
            image/png:
              schema:
                type: string
                format: binary
            image/jpeg:
              schema:
                type: string
                format: binary
        '404':
          description: Image not found

  /user_svc/store_image/v1:
    post:
      summary: Store image/PDF in MinIO and return presigned URL
      description: Stores binary data in MinIO object storage and generates a presigned URL for client access
      operationId: storeImage
      requestBody:
        required: true
        content:
          application/x-protobuf:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                client_url:
                  type: string
                  description: Client callback URL
                pdf_data:
                  type: string
                  format: byte
                  description: PDF binary data to store
      responses:
        '200':
          description: Image stored successfully
          content:
            application/x-protobuf:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  storage_id:
                    type: string
                  presigned_url:
                    type: string
                    description: Temporary S3 presigned URL for client access

  /health:
    head:
      summary: Check service health
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy