{
 "title": "ImageSvc - PromEx Beam Dashboard",
 "description": "All the data that is presented here is captured by the PromEx BEAM plugin (https://github.com/akoutmos/prom_ex/blob/master/lib/prom_ex/plugins/beam.ex)",
 "tags": [
  "PromEx",
  "BEAM",
  "image_svc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Prometheus Job",
    "query": "label_values(image_svc_prom_ex_prom_ex_status_info, job)"
   },
   {
    "name": "instance",
    "label": "Application Instance",
    "query": "label_values(image_svc_prom_ex_prom_ex_status_info{job=\"$job\"}, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "15s, 30s, 1m, 5m, 15m, 30m, 1h" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "The amount of time that has passed since the system has started.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_uptime_milliseconds_count{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "OTP Compiler Options",
   "type": "table",
   "description": "Shows the various options that OTP was compiled with.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"image_svc_prom_ex_beam_system_thread_support_info|image_svc_prom_ex_beam_system_jit_support_info|image_svc_prom_ex_beam_system_smp_support_info|image_svc_prom_ex_beam_system_time_correction_support_info\", job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "OTP Major Version",
   "type": "stat",
   "description": "The OTP major version running the application.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_system_version_info{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Process Count",
   "type": "stat",
   "description": "The number of running BEAM processes currently running.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_process_count{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Information",
   "type": "table",
   "description": "Shows information regarding the schedulers configured for the BEAM instance.",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{__name__=~\"image_svc_prom_ex_beam_system_dirty_cpu_schedulers_info|image_svc_prom_ex_beam_system_dirty_cpu_schedulers_online_info|image_svc_prom_ex_beam_system_dirty_io_schedulers_info|image_svc_prom_ex_beam_system_schedulers_info|image_svc_prom_ex_beam_system_schedulers_online_info|image_svc_prom_ex_beam_system_word_size_bytes_info|image_svc_prom_ex_beam_system_logical_processors_info|image_svc_prom_ex_beam_system_logical_processors_available_info|image_svc_prom_ex_beam_system_logical_processors_online_info\", job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Port Count",
   "type": "stat",
   "description": "The number of currently active ports.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_port_count{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "ETS Table Count",
   "type": "stat",
   "description": "The number of currently allocated ETS tables.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_ets_count{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Limits",
   "type": "table",
   "description": "Shows information regarding the system limits of the BEAM instance.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "{__name__=~\"image_svc_prom_ex_beam_system_ets_limit_info|image_svc_prom_ex_beam_system_port_limit_info|image_svc_prom_ex_beam_system_process_limit_info|image_svc_prom_ex_beam_system_atom_limit_info\", job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "description": "The amount of memory currently allocated by the BEAM.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_memory_allocated_bytes{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Atom Count",
   "type": "stat",
   "description": "The number of atoms currently in the atom table.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_atom_count{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "description": "Stats on the current memory usage.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_memory_allocated_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Total Usage"
    },
    {
     "expr": "image_svc_prom_ex_beam_memory_atom_total_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "image_svc_prom_ex_beam_memory_binary_total_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Binaries"
    },
    {
     "expr": "image_svc_prom_ex_beam_memory_code_total_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "image_svc_prom_ex_beam_memory_ets_total_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "ETS"
    },
    {
     "expr": "image_svc_prom_ex_beam_memory_processes_total_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "image_svc_prom_ex_beam_memory_persistent_term_total_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Persistent Term"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "description": "The number of garbage collection events that are occurring and the number of bytes reclaimed",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "locale", "label": "Garbage Collections" }
   ],
   "targets": [
    {
     "expr": "irate(image_svc_prom_ex_beam_stats_gc_count{job=\"$job\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Garbage Collections"
    },
    {
     "expr": "irate(image_svc_prom_ex_beam_stats_gc_reclaimed_bytes{job=\"$job\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "Normal Scheduler Status",
   "type": "graph",
   "description": "Statistics regarding the normal scheduler.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    {
     "format": "locale",
     "label": "Normal Run Queue (-) / Normal Tasks (+)"
    }
   ],
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_active_task_count{job=\"$job\", instance=\"$instance\", type=\"normal\"}",
     "legendFormat": "Normal Tasks"
    },
    {
     "expr": "0 - image_svc_prom_ex_beam_stats_run_queue_count{job=\"$job\", instance=\"$instance\", type=\"normal\"}",
     "legendFormat": "Normal Run Queue"
    }
   ]
  },
  {
   "title": "Dirty Scheduler Status",
   "type": "graph",
   "description": "Statistics regarding the dirty schedulers.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    {
     "format": "locale",
     "label": "Dirty Run Queue (-) / Dirty Tasks (+)"
    }
   ],
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_active_task_count{job=\"$job\", instance=\"$instance\", type=\"dirty\"}",
     "legendFormat": "Dirty Tasks"
    },
    {
     "expr": "0 - image_svc_prom_ex_beam_stats_run_queue_count{job=\"$job\", instance=\"$instance\", type=\"dirty\"}",
     "legendFormat": "Dirty Run Queue"
    }
   ]
  },
  {
   "title": "VM Load",
   "type": "graph",
   "description": "The number of context switches that have occurred along with the number of reductions.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "locale", "label": "Reduction Count (in Millions)" }
   ],
   "targets": [
    {
     "expr": "irate(image_svc_prom_ex_beam_stats_reduction_count{job=\"$job\", instance=\"$instance\"}[$interval]) / 1000000",
     "legendFormat": "Reductions"
    },
    {
     "expr": "irate(image_svc_prom_ex_beam_stats_context_switch_count{job=\"$job\", instance=\"$instance\"}[$interval])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Active BEAM Processes",
   "type": "graph",
   "description": "The number of running BEAM processes.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "Processes" }
   ],
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_process_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Active Processes"
    }
   ]
  },
  {
   "title": "Atom Table Size",
   "type": "graph",
   "description": "The number of atoms currently in the atom table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale", "label": "Atoms" }
   ],
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_atom_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Active ports"
    }
   ]
  },
  {
   "title": "Port IO",
   "type": "graph",
   "description": "The number of bytes sent and received through ports.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    {
     "format": "Bps",
     "label": "Data Received (-) / Data Sent (+)"
    }
   ],
   "targets": [
    {
     "expr": "0 - irate(image_svc_prom_ex_beam_stats_port_io_byte_count{job=\"$job\", instance=\"$instance\", type=\"input\"}[$interval])",
     "legendFormat": "Data Received"
    },
    {
     "expr": "irate(image_svc_prom_ex_beam_stats_port_io_byte_count{job=\"$job\", instance=\"$instance\", type=\"output\"}[$interval])",
     "legendFormat": "Data Sent"
    }
   ]
  },
  {
   "title": "ETS Tables",
   "type": "graph",
   "description": "The number of active ETS tables.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Tables" }
   ],
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_ets_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Active ETS Tables"
    }
   ]
  },
  {
   "title": "Active Ports",
   "type": "graph",
   "description": "The number of active ports.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Ports" }
   ],
   "targets": [
    {
     "expr": "image_svc_prom_ex_beam_stats_port_count{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "Active Ports"
    }
   ]
  }
 ]
}